Card 7
BrightCoders-Institute/s8pf-s8a1-final-project-team-3 pull request #34
Opened 2024-04-12 23:09 UTC by joseocxmpo

# Description

Designed the screen where you slect your card payment method
- Added Card screen
- Added PaymentMethod component
- Added icons and folloewed ui guidelines

## Screenshots
![image](https://github.com/BrightCoders-Institute/s8pf-s8a1-final-project-team-3/assets/73671543/ee678989-aa15-4f66-966d-f74e038dbc1e)
![image](https://github.com/BrightCoders-Institute/s8pf-s8a1-final-project-team-3/assets/73671543/ad331c5a-ecdb-4470-a819-99d773115579)

2024-04-12 23:25 UTC, juperameza requested changes

2024-04-12 23:25 UTC, juperameza commented on BrightCommers/index.js
>  AppRegistry.registerComponent(appName, () => App);
New line at the end of the file

2024-04-13 00:00 UTC, Oscar-Heredia approved these changes

2024-04-13 00:14 UTC, Antonio3veces3 approved these changes
Well done guys!

2024-04-13 23:44 UTC, JuanequeX approved these changes

2024-04-15 15:51 UTC, Antonio3veces3 approved these changes
Well done guys!

2024-04-15 16:06 UTC, Alfredo20164920 approved these changes

2024-04-15 23:24 UTC, juperameza approved these changes

2024-04-15 23:24 UTC, merged